version: '3.5'
services: 
  mongo:
    container_name: mongo
    image: mongo:${MONGODB_TAG}
    ports: 
      - ${MONGO_EXTERNAL}:${MONGO_INTERNAL}
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
      - ./mongo/db:/data/db
  pyspark:
    container_name: pyspark
    image: jupyter/pyspark-notebook:${PYSPARK_TAG}
    ports: 
      - ${PYSPARK_EXTERNAL}:${PYSPARK_INTERNAL}
    volumes: 
      - ./data:/data
  esri:
    env_file: credentials.env
    container_name: esri
    image: esridocker/arcgis-api-python-notebook:${ESRI_TAG}
    ports: 
      - ${ESRI_EXTERNAL}:${ESRI_INTERNAL}
    volumes: 
      - ./data:/home/jovyan/data
      - ./requirements.txt:/home/jovyan/requirements.txt

networks: 
  neighborhood:
    name: ${DC_NETWORK}
    driver: bridge