version: '3.5'
services: 
  mongo:
    container_name: mongo
    image: mongo:${MONGODB_TAG}
    ports: 
      - ${MONGO_EXTERNAL}:${MONGO_INTERNAL}
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
      - ./persistence/mongo/db:/data/db
  pyspark:
    env_file: credentials.env
    container_name: routefinder
    image: jupyter/pyspark-notebook:${PYSPARK_TAG}
    ports: 
      - ${PYSPARK_EXTERNAL}:${PYSPARK_INTERNAL}
    volumes: 
      - ./data:/data
      - ./dependencies/pyspark.txt:/home/jovyan/requirements.txt
      - ./persistence/pyspark:/home/jovyan/work
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}  
  esri:
    env_file: credentials.env
    container_name: esri
    image: esridocker/arcgis-api-python-notebook:${ESRI_TAG}
    ports: 
      - ${ESRI_EXTERNAL}:${ESRI_INTERNAL}
      - ${GET_DIRECTIONS_EXTERNAL}:${GET_DIRECTIONS_INTERNAL}
    volumes: 
      - ./data:/home/jovyan/data
      - ./dependencies/esri.txt:/home/jovyan/requirements.txt
      - ./persistence/esri:/home/jovyan/work

networks: 
  neighborhood:
    name: ${DC_NETWORK}
    driver: bridge