version: '3.5'
services: 
  mongo:
    container_name: mongo
    image: mongo:${MONGODB_TAG}
    ports: 8080:8080
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  pyspark:
    container_name: pyspark
    image: jupyter/pyspark-notebook:${PYSPARK_TAG}
    ports: 8081:8888



networks: 
  neighborhood:
    